[package]
name = "sngram-benches"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[[bench]]
name = "extract"
path = "src/extract.rs"
harness = false

[[bench]]
name = "query"
path = "src/query.rs"
harness = false

[[bench]]
name = "counter"
path = "src/counter.rs"
harness = false

[dependencies]
sngram = { workspace = true, features = ["learn", "stream"] }
crc32fast = { workspace = true }
rustc-hash = "2.1"
divan = { workspace = true }
tokio = { workspace = true, features = ["rt"] }

[lints]
workspace = true
